### ISSUE TITLE
Resolve undefined button on Google Analytics Events for tracking links clicked on the website

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#33]
Some buttons are undefined on the event google analytics. We need to fix this from the website and google tag manager

**Comment by olasubomi-o** [comment]
![Uploading Screen Shot 2021-03-13 at 11.09.14 AM.png…]()

**Comment by sanmiayotunde** [comment]
In order to resolve some of the undefined showing on the home page, I had to change the following jquery clickable elements to a link
1. Icon to enter Yoruba or Pidgin sub domain.
`<span class="round-icon">➲</span>`
was changed to
`<a class="round-icon"><span class="sr-only">Enter Yoruba Bible Button</span>➲</a>`
