### ISSUE TITLE
Test Mautic when they update to 4.0

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#80]
Let's keep checking on Mautic until they release 4.0 and test whether it's working well with Zapier.

**Comment by sanmiayotunde** [comment]
## HERE IS THE REPLY FROM MAUTIC** 

https://mautic.slack.com/archives/C02HU8K0D/p1618266726002200

Related: #77 

**DaBible Foundation Yesterday at 5:32 PM**
Hi @ everyone, and @Ruth Cheesley (she/her) There is an hot issue that needs to be resolved for Zapier + Mautic integration. I have opened an issue for this, and we will need to triage and resolve the issue.
We discovered that Zapier is unable to send our user data from MailChimp to Mautic. I spent more than 6 hours on this issue on Saturday 10th of April 2021.
The issue is from Mautic because the required URL from Zapier and other n8n./io could not be found. Both Applications failed to push the data to Mautic.
We finally used PieSync which worked, but it’s a premium application of $49 per month.
https://github.com/mautic/mautic/issues/9898

**4 replies**

**Ruth Cheesley (she/her):away:  6 hours ago**
Thanks for flagging it - please do NOT post in multiple channels regardless of how urgent you perceive the issue to be, that is spamming and we do not permit this in this community.

**Ruth Cheesley (she/her):away:  6 hours ago**
If you wish to add a bounty for this issue then do feel free to do so

**Ruth Cheesley (she/her):away:  6 hours ago**
We have a sprint coming up this weekend however with 92 open pull requests that are already waiting to be tested, I highly doubt that we will have someone to work on this issue. Maybe you could join the sprint and help us to test those PR’s so that the existing bug fixes can be merged, hence freeing up contributor time.

**Ruth Cheesley (she/her):away:  6 hours ago**
We are also in the process of testing and releasing an update to the Zapier app which will introduce OAuth2 authorization but that will not be until Mautic 4. The next sprint for Mautic 4 is the weekend after next (fri-sun inclusive) and we are coordinating that in #mautic-4 - we would likewise welcome more testers, including for the Zapier update.

**Comment by emmanlex** [comment]
We tried Mautic again and it worked out and is working pretty well. We are now releasing emails for new signup users  We tried prior to the update and it was an amazing realization. Refer to #81
